### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by afischer** [pennlabs/pennathletics#14]
Who doesn't love them some good documentation. See an excellent example here:
https://github.com/pennlabs/penn-mobile-server/blob/master/README.md

Lol good luck with that markdown table formatting though

**Comment by adamdom** [comment]
Added on new branch. Pull request submitted.

**Comment by afischer** [comment]
Ack! Unless someone else wants it :D

-- 
Andrew Fischer

On December 11, 2015 at 4:45:41 PM, adamdom (notifications@github.com) wrote:

Added on new branch. Pull request submitted.

**Comment by adelq** [comment]
Closed by #16
